<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Harsh_Yashi" failures="1" tests="3" name="Default test" time="58.299" errors="0" timestamp="2024-09-01T15:09:13 SGT">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="20.226"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="28.928"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="8.723">
    <failure type="java.lang.AssertionError" message="Total Reminder Added is not 1 expected [4] but found [0]">
      <![CDATA[java.lang.AssertionError: Total Reminder Added is not 1 expected [4] but found [0]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1407)
at StepDefinitions.ReminderStepDefinition.he_should_see_a_total_of_reminders_added_to_the_list(ReminderStepDefinition.java:52)
at âœ½.he should see a total of 4 reminders added to the list(file:///C:/Users/Harsh%20Singh/Desktop/New%20folder/AutomationScenario/src/test/resources/Features/Reminder.feature:35)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
